/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bfc03e2a-9404-4e64-aa66-75f40fe51667",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3llwmRDOr",
    "aws_user_pools_web_client_id": "1hn872qp978nlb5tdmscrpl4q7",
    "oauth": {},
    "aws_mobile_analytics_app_id": "67f1fa2c13464c14b4d2a6b3549690bb",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
